<MyRoot>:

    random_label: random_label


    BoxLayout:
        orientation: "vertical"
        Label:
            text: "MKApp"
            font_size: 64
            color: 0.95, 0.61, 0.75 , 1
        Label:
            id: random_label
            text: "-"
            font_size: 64
        Button: 
            text: "Generate"
            font_size: 32
            size: 100 , 50
            on_press: root.generate_number()
